name: Data pipeline for loading json files in BigQuery tables

on:
  push:
    branches:
      - main

jobs:
  run-query:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Google Cloud
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install google-cloud-bigquery google-auth pandas db-dtypes

    - name: Authenticate to Google Cloud
      run: |
        echo "${{ secrets.GCP_CREDENTIALS }}" > "${{ github.workspace }}/gha-creds.json"
        export GOOGLE_APPLICATION_CREDENTIALS="${{ github.workspace }}/gha-creds.json"
    
    - name: Load the venues data in BigQuery
      run: |
        python venues.py

    - name: Load the groups data in BigQuery
      run: |
        python groups.py