name: Google Cloud Query

on:
  push:
    branches:
      - main

jobs:
  run-query:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Google Cloud
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install google-cloud-bigquery google-auth pandas db-dtypes

    - name: Authenticate to Google Cloud
      run: |
        echo "${{ secrets.GCP_CREDENTIALS }}" > "${{ github.workspace }}/gha-creds.json"
        export GOOGLE_APPLICATION_CREDENTIALS="${{ github.workspace }}/gha-creds.json"
    
    - name: Create main.py file
      run: |
        echo '
        from google.cloud import bigquery
        import pandas as pd
        
        # Initialize the BigQuery client
        client = bigquery.Client()
        
        # Define the query string
        query = """
          SELECT *
          FROM `striped-torus-445510-c9.football_stats.bundesliga_fixtures_2024_2025`
          LIMIT 10
        """
        
        # Execute the query and fetch the results as a DataFrame
        df = client.query(query).to_dataframe()
        
        # Print the first 5 rows of the DataFrame
        print(df.head())
        ' > main.py

    - name: Run the query
      run: |
        python main.py
