name: Google Cloud Query

on:
  push:
    branches:
      - main

jobs:
  run-query:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      run: |
        echo "${{ secrets.GOOGLE_CLOUD_CREDENTIALS }}" > "${HOME}/gcloud-key.json"
        cat "${HOME}/gcloud-key.json"  # Debugging: Print the file to check its contents (remove this line later)
        gcloud auth activate-service-account --key-file="${HOME}/gcloud-key.json"

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.5.0
      with:
        version: 'latest'

    - name: Set up BigQuery Client
      run: |
        gcloud config set project striped-torus-445510-c9
        gcloud config set account marijnvanaalst@gmail.com

    - name: Run BigQuery Query
      run: |
        bq query --use_legacy_sql=false 'SELECT * FROM `football_stats.bundesliga_fixtures_2024_2025` LIMIT 10;'
