name: Google Cloud Query

on:
  push:
    branches:
      - main

jobs:
  run-query:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Google Cloud
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GOOGLE_CLOUD_CREDENTIALS }}'
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install google-cloud-bigquery google-auth

    - name: Initialize BigQuery Client
      run: |
        python -c "
        import os
        from google.cloud import bigquery
        
        # Set the GOOGLE_APPLICATION_CREDENTIALS environment variable to the credentials file
        os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = os.path.expanduser('$HOME/gcloud-credentials.json')
        
        # Initialize the BigQuery client
        client = bigquery.Client()
        print('BigQuery client initialized.')
        "
